### ISSUE TITLE
Use Sass for styling

### ISSUE THREAD

**Issue by dwzzzl** [TeaInside/Tea-Messenger-Web#22]
Maybe it's a good idea if we use CSS Preprocessors like Sass (or Less) for styling the user interface

**Comment by ammarfaizi2** [comment]
@dwzzzl @dwzzzl I agreed, since I don't have enough experience with Sass, I just assigned you for this one. Can you handle this?

**Comment by dwzzzl** [comment]
@ammarfaizi2 Okay i can handle this
