### ISSUE TITLE
`required` attribute doesn't work on login page due to button type issue.

### ISSUE THREAD

**Issue by ammarfaizi2** [TeaInside/Tea-Messenger-Web#25]
As we could see here, the form doesn't validate that the inputs are not filled.

![sdvsdv](https://user-images.githubusercontent.com/26004054/54270337-c9e0ed80-45b1-11e9-9b11-3c4f282c863b.png)

Why does it happen?
There are some possibilities as far as I know:
1. The sign in button type is not "submit". (The current button type is "button").
2. A related event listener does not listen to the form. It should be **onsubmit** event which listened to `<form>` tag, **not an onclick** event which listened to `<button>` tag.

Take a look here
https://github.com/TeaInside/Tea-Messenger-Web/blob/master/src/components/login/login.component.html#L45

CC: @dwzzzl

**Comment by dwzzzl** [comment]
Yep, it should listen to **onsubmit** event, not **onclick** event. I will working on it
