### ISSUE TITLE
[question] How to deploy in production mode?

### ISSUE THREAD

**Issue by ammarfaizi2** [TeaInside/Tea-Messenger-Web#27]
I want to update our site with the current views (https://messenger.teainside.org)

How can I deploy in production mode?
What command should I use to do it?
Do we need an npm running instance in production server?

I would prefer to static files which served with nginx instead of npm. But, if a running npm instance is needed, I don't have any objection to it, we can use the nginx proxy.

Thanks.

**Comment by ammarfaizi2** [comment]
CC: @dwzzzl

**Comment by dwzzzl** [comment]
I am not experienced with continuous integration/deployment. But you can run command `npm run build:prod`  to build the project in production mode.

**Comment by ammarfaizi2** [comment]
Nice, I just updated the site view.
I decided to close this issue, thanks.
